Repository openblack/openblack, pull requests merged in 2022-08, with the labels that each got.

#534 ci: Add step running on real game data
  .github/workflows/ci-vcpkg.yml
Labels: test

#542 Add new screenshots
  readme.md
Labels: information

#551 metal: Cannot use swizzled texture as framebuffer
  src/3D/LandIsland.cpp
  src/Graphics/FrameBuffer.cpp
Labels: bug, platform-specific: osx

#553 screenshots: try uploading to bwgame.net
  .github/workflows/ci-vcpkg.yml
Labels: test

#552 object: don't asint in metal
  assets/shaders/vs_object.sc
Labels: bug, platform-specific: osx

#554 rendering: Remove Direct3D as an option
  src/main.cpp
Labels: platform-specific: windows

#556 Gui: Use imgui's official SDL2 interface
  .clang-format-ignore
  .github/workflows/ci-vcpkg.yml
  externals/CMakeLists.txt
  externals/imgui_user/imgui_impl_sdl.cpp
  externals/imgui_user/imgui_impl_sdl.h
  src/Debug/Gui.cpp
  src/Debug/Gui.h
  src/Game.cpp
Labels: bug
